export const NEW_BUCKET_REQUEST = "NEW_BUCKET_REQUEST";
export const NEW_BUCKET_SUCCESS = "NEW_BUCKET_SUCCESS";
export const NEW_BUCKET_FAIL = "NEW_BUCKET_FAIL";
export const NEW_BUCKET_RESET = "NEW_BUCKET_RESET";

export const MY_BUCKETS_REQUEST = "MY_BUCKETS_REQUEST";
export const MY_BUCKETS_SUCCESS = "MY_BUCKETS_SUCCESS";
export const MY_BUCKETS_FAIL = "MY_BUCKETS_FAIL";

export const BUCKET_DETAILS_REQUEST = "BUCKET_DETAILS_REQUEST";
export const BUCKET_DETAILS_SUCCESS = "BUCKET_DETAILS_SUCCESS";
export const BUCKET_DETAILS_FAIL = "BUCKET_DETAILS_FAIL";


export const ALL_BUCKETS_REQUEST = "ALL_BUCKETS_REQUEST";
export const ALL_BUCKETS_SUCCESS = "ALL_BUCKETS_SUCCESS";
export const ALL_BUCKETS_FAIL = "ALL_BUCKETS_FAIL";

export const UPDATE_BUCKET_REQUEST = "UPDATE_BUCKET_REQUEST";
export const UPDATE_BUCKET_SUCCESS = "UPDATE_BUCKET_SUCCESS";
export const UPDATE_BUCKET_RESET = "UPDATE_BUCKET_RESET";
export const UPDATE_BUCKET_FAIL = "UPDATE_BUCKET_FAIL";

export const DELETE_BUCKET_REQUEST = "DELETE_BUCKET_REQUEST";
export const DELETE_BUCKET_SUCCESS = "DELETE_BUCKET_SUCCESS";
export const DELETE_BUCKET_RESET = "DELETE_BUCKET_RESET";
export const DELETE_BUCKET_FAIL = "DELETE_BUCKET_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";