export const NEW_CARD_REQUEST = "NEW_CARD_REQUEST";
export const NEW_CARD_SUCCESS = "NEW_CARD_SUCCESS";
export const NEW_CARD_FAIL = "NEW_CARD_FAIL";
export const NEW_CARD_RESET = "NEW_CARD_RESET";

export const MY_CARDS_REQUEST = "MY_CARDS_REQUEST";
export const MY_CARDS_SUCCESS = "MY_CARDS_SUCCESS";
export const MY_CARDS_FAIL = "MY_CARDS_FAIL";
export const ALL_CARD_FAIL = "ALL_CARD_FAIL";

export const CARD_DETAILS_REQUEST = "CARD_DETAILS_REQUEST";
export const CARD_DETAILS_SUCCESS = "CARD_DETAILS_SUCCESS";
export const CARD_DETAILS_FAIL = "CARD_DETAILS_FAIL";


export const ALL_CARDS_REQUEST = "ALL_CARDS_REQUEST";
export const ALL_CARDS_SUCCESS = "ALL_CARDS_SUCCESS";
export const ALL_CARDS_FAIL = "ALL_CARDS_FAIL";

export const UPDATE_CARD_REQUEST = "UPDATE_CARD_REQUEST";
export const UPDATE_CARD_SUCCESS = "UPDATE_CARD_SUCCESS";
export const UPDATE_CARD_RESET = "UPDATE_CARD_RESET";
export const UPDATE_CARD_FAIL = "UPDATE_CARD_FAIL";

export const DELETE_CARD_REQUEST = "DELETE_CARD_REQUEST";
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS";
export const DELETE_CARD_RESET = "DELETE_CARD_RESET";
export const DELETE_CARD_FAIL = "DELETE_CARD_FAIL";
export const REMOVE_CARD_DETAILS = "REMOVE_CARD_DETAILS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";